#!/bin/bash
set -eu
cd "$(dirname "$0")/.."
mkdir -p reports

count_file() {
  file="$1"
  if [ -f "$file" ]; then
    wc -l < "$file" | tr -d ' '
  else
    echo 0
  fi
}

sum_glob() {
  total=0
  for f in "$@"; do
    [ -f "$f" ] || continue
    n=$(wc -l < "$f" | tr -d ' ')
    total=$((total + n))
  done
  echo "$total"
}

router=$(count_file src/ssr.cbl)
config=$(count_file src/config.cbl)
template=$(count_file src/ssrtemplate.cbl)
cgi=$(sum_glob src/cgilib.cbl src/cgihtmlhdr.cbl src/navbuild.cbl)
posts=$(count_file src/postsdata.cbl)
controllers=$(sum_glob src/controllers/*.cbl)
views=$(sum_glob views/*.cow)

total=$((router + config + template + cgi + posts + controllers))

cat > reports/line-count.txt <<EOF
# Generated by scripts/count-lines.sh — non-blank lines approximated via wc -l
feature,files,lines
router (PATH_INFO + method dispatch),src/ssr.cbl,${router}
route table,src/config.cbl,${config}
template engine,src/ssrtemplate.cbl,${template}
CGI POST/cookie/session,cgilib+cgihtmlhdr+navbuild,${cgi}
indexed data (posts.dat),src/postsdata.cbl,${posts}
page controllers,src/controllers/*.cbl,${controllers}
HTML views,views/*.cow,${views}
total_cobol,,${total}
total_views,,${views}
EOF

cat reports/line-count.txt
